#!/usr/bin/env ruby

require 'bundler/setup'
require 'redux_ussd'

class HelloWorld
  include ReduxUssd

  menu do
    screen :index, action: :show_welcome do
      text 'Accept terms and conditions?'
      option :yes, text: 'Yes'
      option :no, text: 'No'
    end

    action :show_welcome do
      push :welcome if state[:options][:option] == :yes
      push :denied_terms if state[:options][:option] == :no
    end

    screen :denied_terms do
      text 'You denied, sorry :('
    end

    screen :welcome, action: :push_welcome do
      text 'Welcome to test service'
      option :deposit, text: 'Deposit money'
      option :balance, text: 'Balance'
    end

    screen :balance do
      text 'Your balance is 20AR.'
    end

    action :push_welcome do
      push state[:options][:option]
    end

    screen :deposit, action: :deposit do
      prompt :amount, text: 'How much?'
    end

    action :deposit do
      push :deposit_success
    end

    screen :deposit_success do
      text "Successfully deposited #{state[:prompt][:values][:amount]}AR"
    end
  end
end

hello_world = HelloWorld.new
hello_world.setup_menu
hello_world.menu.handle_raw_input('')
while true
  puts hello_world.menu.render
  break if hello_world.menu.check_end?
  print '>> '
  input = gets.strip
  hello_world.menu.handle_raw_input(input)
end
