#!/usr/bin/env ruby

require 'bundler/setup'
require 'redux_ussd'

class HelloWorld
  include ReduxUssd

  menu do
    screen :index, action: :show_welcome do
      text "Accept terms and conditions?"
      option :yes, text: 'Yes'
      option :no, text: 'No'
    end

    action :show_welcome do
      return unless static.key?(:name)
      push :welcome if state[:option] == :yes
      push :denied_terms if state[:option] == :no
    end

    screen :denied_terms, force_end: true do
      text 'You denied, sorry :('
    end

    screen :welcome, action: :push_welcome do
      text "Welcome to test service, #{static[:name]}!"
      option :deposit, text: 'Deposit money'
      option :balance, text: 'Balance'
      option :end, text: 'End'
    end

    screen :balance, force_end: true do
      text 'Your balance is 20AR.'
    end

    action :push_welcome do
      force_end if state[:option] == :end
      push state[:option]
    end

    screen :deposit, action: :deposit do
      prompt :amount, text: 'How much?'
    end

    action :deposit do
      push :deposit_success
    end

    screen :deposit_success do
      text "Successfully deposited #{state[:values][:amount]}AR"
    end
  end
end

hello_world = HelloWorld.new
hello_world.setup_menu(static: { name: 'User 1'})
# Initially handle a raw input start the menu.
# It can be used to initialize a menu with use codes e.g, *100#1
hello_world.menu.handle_raw_input('')
while true
  puts hello_world.menu.render
  break if hello_world.menu.end?
  print '>> '
  input = gets.strip
  hello_world.menu.handle_raw_input(input)
end
